### ISSUE TITLE
Home page is broken on some migrated sites.

### ISSUE THREAD

**Issue by Carris-Toupin** [az-digital/az_quickstart#1231]
## Problem/Motivation
The Home page displays the error, 'Page not found'.

### Describe the bug

Home Page/Link:
•	The home link is not working.
•	The title is in Content, but it cannot be viewed or edited.
•	Page not found error.

### To Reproduce

https://live-azs-uxua.pantheonsite.io/

The Home Page is completely broken.
/home (was set as homepage, title: UX@UA: A UX Community at the University of Arizona)

On the UAS site, there is a URL redirect. I am not sure if that affected the migration and is involved in the issue.

## Proposed resolution
TBD

### Expected behavior

For migrated sites to retain similar functionality to UAS sites.

##  Screenshots
![Screen Shot 2022-01-18 at 3 54 12 PM (3)](https://user-images.githubusercontent.com/97066045/150018680-512295d0-c562-49c5-9518-f62ba19200c4.png)

### Desktop (please complete the following information):
Problem exists on all OS’s, Browsers and devices.

Problem exists

**Comment by natebyerley** [comment]
This is generally due to:

1) Config default of /node for <front> page, which can be easily fixed.  Perhaps this is really a ticket to make /home default <front> page url in config. 

2) In some cases this is due to a Carousel issue, whereby each Carousel item on a migrated site must be opened and resaved. In some cases the Carousel url - is lacking a leading "/" which must be fixed before saving. Carousel issues can affect non carousel pages. 

These are not super high priority, though perhaps the /home fix is easy.

**Comment by trackleft** [comment]
Migrating the /home path could be as simple as this?

```
id: az_site_frontpage
label: Site Front Page
migration_group: az_migration
migration_tags:
  - Quickstart Settings Migration

# This will skip processing if the source variable is missing.
source:
  plugin: variable
  variables:
    - site_frontpage
  variables_no_row_if_missing:
    - site_frontpage

process:
  'page/front':
      plugin: az_migrated_path_lookup
        term_migration:
          - az_event_categories
          - az_flexible_page_categories
          - az_news_tags
          - az_person_categories_secondary
          - az_person_categories
        node_migration:
          - az_node_carousel
          - az_node_event
          - az_node_flexible_page
          - az_node_news
          - az_node_person
          - az_node_uaqs_basic_page_to_az_page


destination:
  plugin: config
  config_name: system.site

migration_dependencies:
  optional:
    - az_node_carousel
    - az_node_event
    - az_node_flexible_page
    - az_node_news
    - az_node_person
    - az_node_uaqs_basic_page_to_az_page

```
