### ISSUE TITLE
Redirect Migration Causes Fatal Errors

### ISSUE THREAD

**Issue by rmarsh1ua** [az-digital/az_quickstart#1265]
## Problem/Motivation
After executing a variation of the az_redirects.yml migration against a D7 site, all such redirects in the new quickstart site produced an internal error instead of forwarding the browser.

### To Reproduce

1. Get a sample D7 site ready for migration. Ensure that at least one quickstart page has a url redirect attached to it.
2. From the command line run `drush migrate:import az_redirects`
3. Visit the URL associated with the redirect. Browser reports internal server error.

## Proposed resolution
I started a [fork-branch](https://github.com/rmarsh1ua/az_quickstart/tree/redirect-status-fix) with a solution described [in this post](https://www.drupal.org/project/redirect/issues/3200841#comment-14040845). Let me know if I'm clear to open a PR.

### Expected behavior

The URL should forward as expected.

### Desktop (please complete the following information):
 - Lando stack of quickstart
 - Ubuntu desktop using FF browser

**Comment by trackleft** [comment]
So the default value for the status code, fixes the issue?

**Comment by trackleft** [comment]
Does this work
```
 status_code:
      plugin: default_value
      default_value: 302
      source: status_code
```
Instead of
``` 
 status_code:
    -
      plugin: get
      source: status_code
    -
      plugin: default_value
      default_value: 302
      source: status_code
      ```
