### ISSUE TITLE
ParagraphMappingFlexiblePage Migration Process Not Working Correctly

### ISSUE THREAD

**Issue by rmarsh1ua** [az-digital/az_quickstart#1278]
## Problem/Motivation
I am attempting to use the ParagraphMappingFlexiblePage migration plugin to map more than one nodes from various migration_lookups, as paragraphs, into a single page. What am I finding is that the last source specified will be migrated but all previous sources are ignored. The code doesn't really match how I expect the plugin to work.

### To Reproduce
Try a migration like this:
```
  temp_body_value:
    plugin: migration_lookup
    source: nid
    migration: ua_gc_paragraph

  temp_panel_value:
    plugin: migration_lookup
    source: nid
    migration: ua_gc_panel_group


  field_az_main_content:
    plugin: paragraphs_mapping_flexible_page
    source:
      - '@temp_body_value'
      - '@temp_panel_value'
```

## Proposed resolution
Opening a PR now that refactors the ParagraphMappingFlexiblePage class.

### Expected behavior

In the new implementation the array structure from the $value variable is iterated and mapped into multiple paragraphs.
