### ISSUE TITLE
Replace "@email.arizona.edu" with "@arizona.edu" for all mail fields in migrations.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1430]
## Motivation
Now is as good a time as any to automatically update all email addresses on sites to "@arizona.edu" addresses.

## Proposed Resolution
Add a string replacement plugin step to all email field processes.

```yml
  field_email:
    plugin: str_replace
    case_insensitive: true
    source: email
    search: @email.arizona.edu
    replace: @arizona.edu

```
