### ISSUE TITLE
Break media migrations out into separate migration per bundle. Deprecate az_media migration.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1520]
## Motivation
I think it is probably best to bite the bullet and break az_media into separate migrations for each media type.
While this might be somewhat inconvenient for anyone with additional media types, it could also solve problems they are experiencing with remote content referenced by existing media items.
This would also make it much easier to copy our migrations by entity type for use in custom migrations. 

### Is your feature request related to a problem? Please describe.
Currently the az_media migration is so complex that it is difficult to troubleshoot where problems exist because it maps all fields to all entity types even if they don't actually exist on the destination.

### Describe the solution you'd like
Separate migrations for:
az_image
az_document
az_video
az_remote_video
az_audio

These migrations should be able to map only the fields that exist on each destination.

### Describe alternatives you've considered
Continue troubleshooting on az_media for errors that exist on complex sites.

**Comment by trackleft** [comment]
Example working az_image migration

```
id: az_image
label: Images
migration_group: az_migration
audit: true
migration_tags:
  - Drupal 7
  - Content
  - Quickstart Content Migration
  - Media
source:
  plugin: d7_file_entity_item
  type: image
  CONSTANTS:
    BUNDLE_PREFIX: 'az_'
process:
  uid:
    -
      plugin: migration_lookup
      migration: az_user
      no_stub: true
      source: uid
    -
      plugin: default_value
      default_value: 0
  bundle:
    - plugin: concat
      source:
        - CONSTANTS/BUNDLE_PREFIX
        - bundle
  field_media_az_image/alt:
    - plugin: skip_on_empty
      method: process
      source: 'field_file_image_alt_text/0/value'
  field_media_az_image/title:
    - plugin: skip_on_empty
      method: process
      source: 'field_file_image_title_text/0/value'
  field_media_az_image/target_id:
      - plugin: migration_lookup
        migration:
          - az_files
        source: fid
  field_az_caption:
    - plugin: skip_on_empty
      method: process
      source: 'field_uaqs_caption_text/0/value'
    - plugin: sub_process
      source: field_uaqs_caption_text
      process:
        delta: delta
        value: value
        format:
          plugin: default_value
          default_value: plain_text
  field_az_credit:
    - plugin: skip_on_empty
      method: process
      source: 'field_uaqs_image_credit/0/value'
    - plugin: sub_process
      source: field_uaqs_image_credit
      process:
        delta: delta
        value: value
        format:
          plugin: default_value
          default_value: plain_text
  created: timestamp
  changed: timestamp
  status: status


destination:
  plugin: entity:media

migration_dependencies:
  required:
    - az_user
    - az_files

dependencies:
  enforced:
    module:
      - az_migration
      - az_media
```
