### ISSUE TITLE
az_media maps file_enties that should be mapped to az_remote_video media entities to az_video media entities.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1521]
## Problem/Motivation

Embedded youtube videos should be migrating to az_remote_video media items, instead they are being migrated to az_video, which expects an actual video file, like an mp4.

This causes errors during migration, plus the migration isn't actually successful.

### To Reproduce
Create a source site based on Quickstart 1
Create a destination site based on Quickstart 2

-- on the source site
Add an mp4 video file
Add an embedded video from Youtube.

-- on the destination site
Run the az_migration group.

View how the youtube video creates a new az_video media item.
View how the mp4 creates a new az_video media item.

## Proposed resolution
Create separate migrations for each media types: See #1520 

### Expected behavior

Youtube videos migrate as az_remote_video, with just the url in the Video URL field `url`
If there is a cover image on the source site (`field_uaqs_photo`), that should be migrated into the cover image field on the destination site (`field_media_az_image`).

**Comment by trackleft** [comment]
I propose breaking video out into two separate migrations.
`az_media_az_video.yml`
```
id: az_media_az_video
label: Images
migration_group: az_migration
audit: true
migration_tags:
  - Drupal 7
  - Content
  - Quickstart Content Migration
  - Media
source:
  plugin: d7_file_entity_item
  type: video
process:
  pseudo_check_if_oembed:
    - plugin: skip_on_value
      value:
        - "video/oembed"
      method: row
      source: filemime
  bundle:
    - plugin: default_value
      default_value: 'az_video'
  uid:
    -
      plugin: migration_lookup
      migration: az_user
      no_stub: true
      source: uid
    -
      plugin: default_value
      default_value: 0
  field_media_az_video_file/target_id:
      - plugin: migration_lookup
        migration:
          - az_files
        source: fid

  created: timestamp
  changed: timestamp
  status: status
  name:
    - plugin: skip_on_empty
      source: filename
      method: process


destination:
  plugin: entity:media

migration_dependencies:
  required:
    - az_user
    - az_files

dependencies:
  enforced:
    module:
      - az_migration
      - az_media
   ```
   `az_media_az_remote_video.yml`
   ```
   id: az_media_az_remote_video
migration_group: az_migration
audit: true
migration_tags:
  - Drupal 7
  - Content
  - Quickstart Content Migration
  - Media
source:
  plugin: d7_file_entity_item
  type: video
  CONSTANTS:
    BUNDLE_PREFIX: 'az_'
process:
  pseudo_check_if_oembed:
    - plugin: skip_on_value
      not_equals: true
      value:
        - "video/oembed"
      method: row
      source: filemime
  bundle:
    - plugin: default_value
      default_value: 'az_remote_video'
  uid:
    -
      plugin: migration_lookup
      migration: az_user
      no_stub: true
      source: uid
    -
      plugin: default_value
      default_value: 0
  created: timestamp
  changed: timestamp
  status: status
  name:
    - plugin: skip_on_empty
      source: filename
      method: process
  'field_media_az_oembed_video/0/value':
    - plugin: str_replace
      source: uri
      search: "oembed://"
      replace: ''
    - plugin: callback
      callable: urldecode
  field_media_az_image:
    - plugin: gate
      source: field_uaqs_photo
      use_as_key: filemime
      valid_keys:
        - video/oembed
      key_direction: unlock
    - plugin: sub_process
      source: field_uaqs_photo
      process:
        delta: delta
        target_id:
        -
          plugin: migration_lookup
          source: fid
          migration:
            - az_files

destination:
  plugin: entity:media

migration_dependencies:
  required:
    - az_user
    - az_files

dependencies:
  enforced:
    module:
      - az_migration
      - az_media
   ```
