### ISSUE TITLE
Add `devel` and enable theme debugging to lando tooling

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1530]
## Motivation
As a developer, often I have to enable theme debugging when creating quickstart pull-requests, and the current procedure, while in the docs is a pain.

## Proposed Resolution
Add lando tooling, so I don't have to remember how to do this, or look it up.

### Describe the solution you'd like
```
  # Enable theme debugging and devel.
  devel:
    service: appserver
    user: root
    cmd:
      - echo "Enabling theme debugging and devel..."
      - chmod 755 /app/web/sites/default/settings.php
      - /app/vendor/bin/drush --root=/app/web en -y devel
      - /app/vendor/bin/drupal --root=/app/web site:mode dev
      - chmod 644 /app/web/sites/default/settings.php
```

Then update the CONTRIBUTING docs to let people know about it.

### Describe alternatives you've considered
Leave everything as it is.
