### ISSUE TITLE
Use field_link process plugin for migrating carousel links.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1674]
Oftentimes a migrated site has a carousel on the front page which links to content within the site, and it is not migrated correctly, giving the illusion that the site is broken beyond repair. 
```
  field_az_link:
    plugin: field_link
    source: field_uaqs_link
    uri_scheme: "https://"
```
Should replace: 
https://github.com/az-digital/az_quickstart/blob/9f60b686d66d664a6111c599300596ddf809fc46/modules/custom/az_migration/migrations/migrate_plus.migration.az_node_carousel.yml#L35-L53
