### ISSUE TITLE
Add entity_embed_process process plugin to az_paragraph_html migration for text areas.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1839]
## Motivation
Looks like we forgot to add entity_embed_process plugin to the text area creation option.

### Describe the solution you'd like
Update az_paragraph_html migration with the entity_embed_process plugin for the text area creation option.
```

  field_az_text_area:
    plugin: sub_process
    source: field_uaqs_html
    process:
      delta: delta
       value:
          plugin: az_entity_embed_process
          source: value
      format:
        plugin: default_value
        default_value: az_standard


```
