### ISSUE TITLE
Enable dependabot for GitHub actions workflows

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2157]
## Motivation
Dependabot now supports tracking updates for GitHub actions workflows.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

## Proposed Resolution

Add this to our dependabot config:
```
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
```
