### ISSUE TITLE
Change argument array syntax in .service.yml files to make it easier to review changes.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#3022]
## Conditions of satisfaction
- [ ] All service.yml files have been updated with new array syntax.

Example:

**From**
```
  az_core.override_import:
    class: Drupal\az_core\AZConfigOverride
    arguments: ['@config.factory', '@extension.list.module', '@config_provider.collector', '@config_sync.snapshotter', '@config_update.config_list', '@module_handler', '@logger.channel.az_core']

```
**To**
```
  az_core.override_import:
    class: Drupal\az_core\AZConfigOverride
    arguments: 
      - '@config.factory'
      - '@extension.list.module'
      - '@config_provider.collector'
      - '@config_sync.snapshotter'
      - '@config_update.config_list'
      - '@module_handler'
      - '@logger.channel.az_core'
```
