### ISSUE TITLE
Add phpcbf command to lando file to fix codesniffer problems automatically.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#466]
## Motivation
When I see that codesniffer throws errors on probo, many times there is a message that says that PHPCBF can fix them automatically. I want auto fixing of my syntax errors.

## Proposed Resolution
In the .lando.yml file we can add this block under tooling.
```
  # Provide PHPCBF tooling to fix coding standards.
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf --standard=web/profiles/custom/az_quickstart/phpcs.xml.dist

```
Then, to use, we should be able to do `phpcbf <filepath>` to fix the errors on that file.
We already have phpcbf installed, so using it should be a breeze.

additionally we should add 
```
	.phpcs-cache

```

to our .gitignore
