### ISSUE TITLE
Quickstart version indicator enhancements

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#515]
## Motivation
In #368 we added a basic Quickstart version indicator to the admin toolbar.  The implementation that was adopted was a very basic, MVP implementation and there are several follow-up improvements that are needed.

## Proposed Resolution

Follow-up items identified in #368 

- Add more specific class and stylesheet to float right
- Link to Quickstart documentation for content editors / Link to Quickstart settings page for content admins ? (Note: a link to quickstart.arizona.edu has been added as of 7/7/21 and there was discussion that it made the most sense for content admins for the link to go to the same place).
- Add more specific version indicator to Quickstart settings page?

**Comment by trackleft** [comment]
Ran across this while doing something else.

Add version key to az_quickstart.info.yml file

Then, in https://github.com/az-digital/az_quickstart/blob/main/.github/workflows/create-release.yml#L20 line 19 add something like this:
```
      - name: Update az_quickstart version number
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'az_quickstart.info.yml'
          propertyPath: 'version'
          value: ${{ github.event.inputs.version }}
          commitChange: false
          
        
```
See https://github.com/fjogeleit/yaml-update-action
